---
- command: timedatectl set-ntp true

- template:
    src: mirrorlist.j2
    dest: /etc/pacman.d/mirrorlist

- file:
    src: /usr/share/zoneinfo/US/Eastern
    dest: /etc/localtime
    state: link 

- command: hwclock--systohc

- template:
    src: local.gen
    dest: /etc/local.gen


- command: locale-gen

- template: 
    src: hostname
    dest: /etc/hostname
